### ISSUE TITLE
When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding 

### ISSUE THREAD

**Issue by CAIJUN111** [nopnop2002/multipart-upload-server#2]
caijun01@caijun01-virtual-machine:~/multipart-upload-server/tornado$ python upload.py
WARNING:root:UPLOAD_DIR [/home/caijun01/multipart-upload-server/tornado/uploaded] not found. Create this
Traceback (most recent call last):
  File "upload.py", line 21, in <module>
    os.mkdir(UPLOAD_DIR)
OSError: [Errno 13] Permission denied: '/home/caijun01/multipart-upload-server/tornado/uploaded'
caijun01@caijun01-virtual-machine:~/multipart-upload-server/tornado$ sudo SError: [Errno 13] Permission denied: '/home/caijun01/multipart-upload-server/tornado/uploaded'
sudo: SError:：找不到命令
caijun01@caijun01-virtual-machine:~/multipart-upload-server/tornado$ sudo python upload.py
WARNING:root:UPLOAD_DIR [/home/caijun01/multipart-upload-server/tornado/uploaded] not found. Create this
^CTraceback (most recent call last):
  File "upload.py", line 158, in <module>
    tornado.ioloop.IOLoop.current().start()
  File "/home/caijun01/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 1048, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt

I just executed the documentation "README.cn" in this program.
![image](https://user-images.githubusercontent.com/96687945/178929220-735aca3b-7e28-4a0c-a0ea-d657ea8f74ae.png)

**Comment by nopnop2002** [comment]
I updated README.

Use pytho3 instead python.

**Comment by CAIJUN111** [comment]
thank you!
Your program is&nbsp;&nbsp;amazing !
Whether the ESP32 program that uploads files associated with this server supports esp32S3 ?


The newer MCU can provide a better experience, I tried to compile with esp32S3 and failed, could you tell me how to modify the program to accommodate esp32 S3!



thanks again!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nopnop2002/multipart-upload-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nopnop2002/multipart-upload-server] When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding  (Issue #2)





 
I updated README.
 
Use pytho3 instead python.

**Comment by nopnop2002** [comment]
>I tried to compile with esp32S3 and failed, could you tell me how to modify the program to accommodate esp32 S3!

Just wait.

**Comment by nopnop2002** [comment]
>I tried to compile with esp32S3 and failed


Try latest.

https://github.com/nopnop2002/esp-idf-multipart-upload

**Comment by CAIJUN111** [comment]
Hi!


I have another question ,if I want to put a string in my HTTP post form-data,&nbsp;as&nbsp;shown&nbsp;in&nbsp;the&nbsp;following&nbsp;figure&nbsp;&nbsp;, so how do I do that?&nbsp;










thanks in advance!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nopnop2002/multipart-upload-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nopnop2002/multipart-upload-server] When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding  (Issue #2)





  
I tried to compile with esp32S3 and failed
  
Try latest.
 
https://github.com/nopnop2002/esp-idf-multipart-upload

**Comment by nopnop2002** [comment]
This may help you.

https://github.com/espressif/esp-idf/tree/master/examples/protocols/http_server/file_serving

https://github.com/nopnop2002/esp-idf-web-form

**Comment by CAIJUN111** [comment]
Hi,@nopnop2002,Excuse me, maybe I should clarify my question.



I just want to add a transfer tag to your project&nbsp;nopnop2002/esp-idf-multipart-upload: A multipart file upload example for esp-idf (github.com),



As the red arrow points to in the picture below,
![image](https://user-images.githubusercontent.com/96687945/179434622-bb4009f3-990e-4c1a-8a9b-4d4585fcd626.png)



The picture shows the result I want





when I upload a file,I need add a key&nbsp;

&nbsp;
![image](https://user-images.githubusercontent.com/96687945/179434656-44a27f49-dc21-4112-9c92-a8fa4083a593.png)



and&nbsp;Here's how I did it

![image](https://user-images.githubusercontent.com/96687945/179434667-86ed857c-a186-4345-b640-9d4a852958b3.png)




But THAT's what I get all the time

![image](https://user-images.githubusercontent.com/96687945/179434684-22b4af9e-f7ad-47b5-bbfe-9260b6412b50.png)



I hope I can get your advice,thanks in advance







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nopnop2002/multipart-upload-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nopnop2002/multipart-upload-server] When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding  (Issue #2)





 
This may help you.
 
https://github.com/nopnop2002/esp-idf-web-form

**Comment by CAIJUN111** [comment]
Excuse me, maybe I should clarify my question.



I just want to add a transfer tag to your project nopnop2002/esp-idf-multipart-upload: A multipart file upload example for esp-idf (github.com),



As the red arrow points to in the picture below,



The picture shows the result I want





when I upload a file,I need add a key 

&nbsp;


and Here's how I did it





But THAT's what I get all the time












I hope I can get your advice,thanks in advance


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nopnop2002/multipart-upload-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nopnop2002/multipart-upload-server] When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding  (Issue #2)





 
This may help you.
 
https://github.com/nopnop2002/esp-idf-web-form

**Comment by nopnop2002** [comment]
>I just want to add a transfer tag to your project 

What is "transfer tag" ?

>As the red arrow points to in the picture below,The picture shows the result I want

I can’t view your pictire that you want.

**Comment by CAIJUN111** [comment]
> > I just want to add a transfer tag to your project
> 
> What is "transfer tag" ?
 @nopnop2002 
Sorry, I sent the message through the email, you may not see the photo, I will send again ，
The picture shows the result I want 
![image](https://user-images.githubusercontent.com/96687945/179435226-9db3ba7e-03be-4c59-bf72-dee39c86ba6a.png)
![image](https://user-images.githubusercontent.com/96687945/179435255-d2aae36d-08ff-4829-8bf1-961b7321a767.png)

when I upload a file,I need add a key
and Here's how I did it
![image](https://user-images.githubusercontent.com/96687945/179435303-37fb1a84-bc96-40f1-8454-5734001cecf2.png)
But THAT's what I get all the time
![image](https://user-images.githubusercontent.com/96687945/179435324-ca51dc6d-8476-40ec-bcbb-4f4070bb5a6b.png)

**Comment by nopnop2002** [comment]
[upfile] is defined here.

https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L129

https://github.com/nopnop2002/multipart-upload-server/blob/main/tornado/upload.py#L119

If you use something other than [upfile], you need to change it.


You need to look closely at this output.


https://github.com/nopnop2002/multipart-upload-server/blob/main/tornado/upload.py#L117

https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L115

**Comment by CAIJUN111** [comment]
> [upfile] is defined here.
> 
> https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L129
> 
> https://github.com/nopnop2002/multipart-upload-server/blob/main/tornado/upload.py#L119
> 
> If you use something other than [upfile], you need to change it.
> 
> You need to look closely at this output.
> 
> https://github.com/nopnop2002/multipart-upload-server/blob/main/tornado/upload.py#L117
> 
> https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L115

@nopnop2002 
I don't think uoload.py needs to be modified ,Because I use the Postman client(an APP for testing HTTP and other protocols),I can complete HTTP protocol upload in the following format  Through the unmodified file server.
![image](https://user-images.githubusercontent.com/96687945/179437279-1ad532d6-4b7f-4d45-87b2-acd1d4d6ac8f.png)
So I think I need to change the procedure for uploading files
![image](https://user-images.githubusercontent.com/96687945/179437466-cef33490-315a-4db2-b71e-2e59bf7a0650.png)
I think there is something wrong with the HTTP request body"" I wrote,In the 141 to 143 code snippet. 
"sprintf(header, "Content-Disposition: form-data; name=\"equipmentId\";\r\n\r\n\"%s\"\r\n",EQUIMENTID);"
Can you give me some advice? Thanks in advance
`/* HTTP POST Example using plain POSIX sockets

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_log.h"

#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/sys.h"
#include "lwip/netdb.h"
#include "lwip/dns.h"

#include "voice_upload.h"

/* Constants that are configurable in menuconfig */

#define CONFIG_WEB_SERVER "192.168.1.112"
#define CONFIG_WEB_PORT "8080"
#define CONFIG_WEB_PATH "/upload_multipart"


// #define CONFIG_WEB_SERVER "124.70.57.212"
// #define CONFIG_WEB_PORT "80"
// #define CONFIG_WEB_PATH "/iot/iotdevice/upPic"

#define EQUIMENTID "31017619"

#define BOUNDARY "X-ESPIDF_MULTIPART"

extern QueueHandle_t xQueueRequest;
extern QueueHandle_t xQueueResponse;

static const char *TAG = "post_voice";

char BODY[1024];

void http_post_task(void *pvParameters)
{
	const struct addrinfo hints = 
    {
		.ai_family = AF_INET,
		.ai_socktype = SOCK_STREAM,
	};
	struct addrinfo *res;
	struct in_addr *addr;
	char recv_buf[64];

	REQUEST_t requestBuf;
	RESPONSE_t responseBuf;

	while(1) 
    {
		ESP_LOGI(TAG,"Waitting....");
		xQueueReceive(xQueueRequest, &requestBuf, portMAX_DELAY);
		ESP_LOGI(TAG,"requestBuf.command=%d", requestBuf.command);
		if (requestBuf.command == CMD_HALT) break;

		ESP_LOGI(TAG,"requestBuf.localFileName=%s", requestBuf.localFileName);
		ESP_LOGI(TAG,"requestBuf.remoteFileName=%s", requestBuf.remoteFileName);
		struct stat statBuf;
		if (stat(requestBuf.localFileName, &statBuf) == 0) 
		{
			ESP_LOGI(TAG, "st_size=%d", (int)statBuf.st_size);
		} 
		else 
		{
			strcpy(responseBuf.response,"local file not found");
			xQueueSend(xQueueResponse, &responseBuf, 10);
			ESP_LOGE(TAG, "stat fail");
			continue;
		}

		int err = getaddrinfo(CONFIG_WEB_SERVER, CONFIG_WEB_PORT, &hints, &res);

		if(err != 0 || res == NULL) 
		{
			strcpy(responseBuf.response,"DNS lookup failed");
			xQueueSend(xQueueResponse, &responseBuf, 10);
			ESP_LOGE(TAG, "DNS lookup failed err=%d res=%p", err, res);
			vTaskDelay(1000 / portTICK_PERIOD_MS);
			continue;
		}

		/* Code to print the resolved IP.
		   Note: inet_ntoa is non-reentrant, look at ipaddr_ntoa_r for "real" code */
		addr = &((struct sockaddr_in *)res->ai_addr)->sin_addr;
		ESP_LOGI(TAG, "DNS lookup succeeded. IP=%s", inet_ntoa(*addr));

		int s = socket(res->ai_family, res->ai_socktype, 0);
		if(s < 0) 
		{
			strcpy(responseBuf.response,"Failed to allocate socket");
			xQueueSend(xQueueResponse, &responseBuf, 10);
			ESP_LOGE(TAG, "... Failed to allocate socket.");
			freeaddrinfo(res);
			vTaskDelay(1000 / portTICK_PERIOD_MS);
			continue;
		}
		ESP_LOGI(TAG, "... allocated socket");

		if(connect(s, res->ai_addr, res->ai_addrlen) != 0) 
		{
			strcpy(responseBuf.response,"socket connect failed");
			xQueueSend(xQueueResponse, &responseBuf, 10);
			ESP_LOGE(TAG, "... socket connect failed errno=%d", errno);
			close(s);
			freeaddrinfo(res);
			vTaskDelay(4000 / portTICK_PERIOD_MS);
			continue;
		}

		ESP_LOGI(TAG, "... connected");
		freeaddrinfo(res);

		char HEADER[512];
		char header[128];

		sprintf(header, "POST %s HTTP/1.1\r\n", CONFIG_WEB_PATH);
		strcpy(HEADER, header);
		sprintf(header, "Host: %s:%s\r\n", CONFIG_WEB_SERVER, CONFIG_WEB_PORT);
		strcat(HEADER, header);
		sprintf(header, "User-Agent: esp-idf/%d.%d.%d esp32\r\n", ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH);
		strcat(HEADER, header);

		sprintf(header, "Accept: */*\r\n");
		strcat(HEADER, header);
		sprintf(header, "Content-Type: multipart/form-data; boundary=%s\r\n", BOUNDARY);
		strcat(HEADER, header);

		sprintf(header, "--%s\r\n", BOUNDARY);
		strcpy(BODY, header);
		//ID_data
		sprintf(header, "Content-Disposition: form-data; name=\"equipmentId\";\r\n\r\n\"%s\"\r\n",EQUIMENTID);
		strcat(BODY, header);
		
		sprintf(header, "Content-Type: application/octet-stream\r\n\r\n");
		strcat(BODY, header);
		

		sprintf(header, "--%s\r\n", BOUNDARY);
		strcat(BODY, header);

		//audio
		sprintf(header, "Content-Disposition: form-data; name=\"upfile\"; filename=\"%s\"\r\n", requestBuf.remoteFileName);
		strcat(BODY, header);

		sprintf(header, "Content-Type: application/octet-stream\r\n\r\n");
		strcat(BODY, header);

		char END[128];
		sprintf(header, "\r\n--%s--\r\n\r\n", BOUNDARY);
		strcpy(END, header);
		
		int dataLength = strlen(BODY) + strlen(END) + statBuf.st_size + strlen(EQUIMENTID);
		sprintf(header, "Content-Length: %d\r\n\r\n", dataLength);
		strcat(HEADER, header);

		ESP_LOGE(TAG, "HEADER: [%s]", HEADER);
		if (write(s, HEADER, strlen(HEADER)) < 0) 
		{
			ESP_LOGE(TAG, "... socket send failed");
			close(s);
			vTaskDelay(4000 / portTICK_PERIOD_MS);
			continue;
		}
		ESP_LOGI(TAG, "HEADER socket send success");

		ESP_LOGE(TAG, "BODY: [%s]", BODY);
		if (write(s, BODY, strlen(BODY)) < 0) 
		{
			ESP_LOGE(TAG, "... socket send failed");
			close(s);
			vTaskDelay(4000 / portTICK_PERIOD_MS);
			continue;
		}
		ESP_LOGI(TAG, "BODY socket send success");


	
		// if (write(s, "31017619\r\n", 12) < 0) 
		// {
		// 	ESP_LOGE(TAG, "... socket send failed");
		// 	close(s);
		// }
		// else
		// {
		// 	ESP_LOGE(TAG, "write ID");
		// }
	

		//打开文件，将文件放到缓存区dataBuffer，再上传
		FILE* f=fopen(requestBuf.localFileName, "rb");
		uint8_t dataBuffer[128];
		if (f == NULL) 
		{
			ESP_LOGE(TAG, "Failed to open file for reading");
		}
		while(!feof(f)) 
		{
			int len = fread(dataBuffer, 1, sizeof(dataBuffer), f);
			if (write(s, dataBuffer, len) < 0) 
			{
				ESP_LOGE(TAG, "... socket send failed");
				close(s);
				vTaskDelay(4000 / portTICK_PERIOD_MS);
				continue;
			}
		}
		fclose(f);


		ESP_LOGI(TAG, "DATA socket send success");

		if (write(s, END, strlen(END)) < 0) 
		{
			ESP_LOGE(TAG, "... socket send failed");
			close(s);
			vTaskDelay(4000 / portTICK_PERIOD_MS);
			continue;
		}
		ESP_LOGI(TAG, "END socket send success");

		struct timeval receiving_timeout;
		receiving_timeout.tv_sec = 5;
		receiving_timeout.tv_usec = 0;
		if (setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &receiving_timeout,sizeof(receiving_timeout)) < 0) 
		{
			ESP_LOGE(TAG, "... failed to set socket receiving timeout");
			close(s);
			vTaskDelay(4000 / portTICK_PERIOD_MS);
			continue;
		}
		ESP_LOGI(TAG, "... set socket receiving timeout success");

		/* Read HTTP response */
		int readed;
		bzero(responseBuf.response, sizeof(responseBuf.response));
		do 
		{
			bzero(recv_buf, sizeof(recv_buf));
			ESP_LOGD(TAG, "Start read now=%d", xTaskGetTickCount());
			readed = read(s, recv_buf, sizeof(recv_buf)-1);
			ESP_LOGD(TAG, "End	 read now=%d readed=%d", xTaskGetTickCount(), readed);
			#if 0
			for(int i = 0; i < readed; i++) {
				putchar(recv_buf[i]);
			}
			#endif
			strcat(responseBuf.response, recv_buf);
		} while(readed > 0);
		#if 0
		printf("\n");
		#endif

		/* send HTTP response */
		if (xQueueSend(xQueueResponse, &responseBuf, 10) != pdPASS) {
			ESP_LOGE(TAG, "xQueueSend fail");
		}

		ESP_LOGI(TAG, "... done reading from socket. Last read return=%d errno=%d.", readed, errno);
		close(s);

	}
}
`

**Comment by nopnop2002** [comment]
You need to find out the difference between the messages notified to the server side when using the Postman client and when using the ESP32.


You can see the message notified to the server side here.

https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L112

**Comment by CAIJUN111** [comment]
> You need to find out the difference between the messages notified to the server side when using the Postman client and when using the ESP32.
> 
> You can see the message notified to the server side here.
> 
> https://github.com/nopnop2002/multipart-upload-server/blob/main/flask/upload.py#L112

Thank you for your patient answer，The method you offered doesn't seem to work. upload.py can not get me many messages .i use wireshark catch the http massage ，I'm just gonna have to reprogram it, try to get to the bottom of  http form-data.
thanks again!

**Comment by nopnop2002** [comment]
>i use wireshark catch the http massage


This is the best way.

**Comment by CAIJUN111** [comment]
Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nopnop2002/multipart-upload-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nopnop2002/multipart-upload-server] When I performed this step"sudo python upload.py", Ubuntu was stuck.  Not proceeding  (Issue #2)





  
I tried to compile with esp32S3 and failed
  
Try latest.
 
https://github.com/nopnop2002/esp-idf-multipart-upload
